swagger: "2.0"
info:
  title: bank/v1/bank.proto
  version: version not set
tags:
  - name: BankService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/banks/{id}:
    get:
      operationId: BankService_GetBank
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetBankResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      tags:
        - BankService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
  v1Bank:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
  v1GetBankResponse:
    type: object
    properties:
      data:
        $ref: '#/definitions/v1Bank'
